name = "ParamIO"
uuid = "938a3ac2-d340-473c-bcf1-88af577e4ccf"
version = "0.1.0"
authors = ["sota shimozono <shimozono-sota631@g.ecc.u-tokyo.ac.jp>"]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
